name: Deploy Express.js App to EC2

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Download SQLite database from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_DB_FILE_PATH: ${{ secrets.S3_DB_FILE_PATH }}
        run: |
          aws s3 cp s3://$S3_BUCKET_NAME/$S3_DB_FILE_PATH ./database/quran_main.db

      - name: Install dependencies
        run: npm install

      - name: Build the project (if needed)
        run: npm run build

      - name: Zip the project (excluding node_modules)
        run: |
          zip -r app.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: Copy the zip file to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -o StrictHostKeyChecking=no -i deploy_key.pem app.zip $EC2_USER@$EC2_HOST:/home/ubuntu/app.zip

      - name: Unzip and set up on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $EC2_USER@$EC2_HOST "
            cd /home/ubuntu &&
            unzip -o app.zip -d app &&
            cd app &&
            npm install --production &&
            pm2 restart all || pm2 start npm --name 'quran-backend' -- start
          "
